//PRODUCTS
export const CREATE_PRODUCT = 'CREATE_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

//CATEGORY
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// SELLER
export const FETCH_SELLER = 'FETCH_SELLER';
export const CREATE_SELLER = 'CREATE_SELLER';
export const FETCH_SELLER_BY_ID = 'FETCH_SELLER_BY_ID';
export const UPDATE_SELLER = 'UPDATE_SELLER';
export const DELETE_SELLER = 'DELETE_SELLER';

// USER
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID';